### ISSUE TITLE
Non-Dependabot PRs do not auto_release

### ISSUE THREAD

**Issue by JamesDawson** [endjin/pr-autoflow#34]
`dependabot-pr-parser` cannot currently distinguish between uninteresting Dependabot PRs and regular PRs raised by developers.  This then results in regular PRs being unable to trigger the `auto_release` workflow.

Additionally, manually applying the `pending_release` label to the regular PR and triggering `auto_release` directly fails due to the `no_release` label check failing, which in turn is caused by the lack of a PR context from the triggering event.

**Comment by MikeLarah** [comment]
We can add a new job to `dependabot_approve_and_label` which adds the `pending_release` label to the PR if it is opened by an actor other than dependabot
